# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Lp_norm <- function(t_vector, X, p) {
    .Call(`_spatialquantile_Lp_norm`, t_vector, X, p)
}

crossvalidation <- function(t_vector_X, X_static, t_vector_Y, Y_static, method_for_h, type, Kernel) {
    .Call(`_spatialquantile_crossvalidation`, t_vector_X, X_static, t_vector_Y, Y_static, method_for_h, type, Kernel)
}

kernel <- function(u, Kernel) {
    .Call(`_spatialquantile_kernel`, u, Kernel)
}

kernelweights <- function(x, X_static, t_vector, h, Kernel) {
    .Call(`_spatialquantile_kernelweights`, x, X_static, t_vector, h, Kernel)
}

rcpparma_hello_world <- function() {
    .Call(`_spatialquantile_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_spatialquantile_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_spatialquantile_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_spatialquantile_rcpparma_bothproducts`, x)
}

g_function_weighted <- function(X_local, Q_local, weights_local, u_local) {
    .Call(`_spatialquantile_g_function_weighted`, X_local, Q_local, weights_local, u_local)
}

spatialquantile <- function(Data, Weights, u_index, c, t_vector) {
    .Call(`_spatialquantile_spatialquantile`, Data, Weights, u_index, c, t_vector)
}

spatialquantileconfidenceset <- function(Data, Weights, u_index, c, t_vector, alpha) {
    .Call(`_spatialquantile_spatialquantileconfidenceset`, Data, Weights, u_index, c, t_vector, alpha)
}

wsdrank <- function(X_to_rank, X_data, X_data_weights, t_vector) {
    .Call(`_spatialquantile_wsdrank`, X_to_rank, X_data, X_data_weights, t_vector)
}

